# Adapted from https://github.com/nanoninja/docker-nginx-php-mysql.
version: '3'
services:
    web:
        image: nginx:1.15.10-alpine
        volumes:
          - ./nginx.conf:/etc/nginx/conf.d/default.conf
          # We must mount to `/var/www/html/public` on both the `web` container
          # and the `php` container, because Nginx will return a 404 error if
          # the file isn't found in its own filesystem.
          - .:/var/www/html/public
        ports:
          - 8080:80
        depends_on:
          - php
          - mysql

    php:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
          - .:/var/www/html/public
        depends_on:
          - mysql

    mysql:
        image: mysql
        environment:
          - MYSQL_DATABASE=test
          - MYSQL_ROOT_PASSWORD=toor
